services:
  ziti-tunnel:
    image: openziti/ziti-edge-tunnel:1.11.2
    container_name: storage_ziti_tunnel
    restart: unless-stopped
    network_mode: host
    privileged: true
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /volume1/docker/_synology_configs/ziti-edge-tunnel:/ziti-edge-tunnel
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    command: ["run", "--dns-upstream", "192.168.5.162"]
    environment:
      - ZITI_ENROLL_TOKEN=${ZITI_ENROLL_TOKEN}
