services:
  dozzle-agent:
    image: amir20/dozzle:v10.3.0
    container_name: openziti_ii_dozzle_agent
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
    restart: unless-stopped
    environment:
    - DOZZLE_HOSTNAME=openziti_ii
    network_mode: bridge
