services:
  dozzle-agent:
    image: amir20/dozzle:v10.5.0
    command: agent
    container_name: media_servers_dozzle_agent
    #dns:
    #  - 100.64.0.2
    #  - 192.168.5.162
    #  - 192.168.5.92
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
    environment:
    - DOZZLE_HOSTNAME=media_servers
    restart: unless-stopped
    network_mode: bridge
