services:
  ziti-router:
    image: netfoundry/autonomous-router:latest
    container_name: middleware_ziti_router
    restart: unless-stopped
    network_mode: host
    pid: host
    cap_add:
      - NET_ADMIN
    environment:
      - REG_KEY=${REG_KEY}
      - TUNNEL_MODE=auto
    volumes:
      - /docker/configs/netfoundry:/etc/netfoundry

  dns-register:
    image: alpine:latest
    container_name: middleware_ziti_dns_register
    restart: "no"
    network_mode: host
    pid: host
    entrypoint: ["/bin/sh", "-c", "apk add --no-cache systemd-resolvectl >/dev/null 2>&1 || apk add --no-cache systemd >/dev/null 2>&1; sleep 45; resolvectl dns eth0 $$(hostname -i | awk '{print $$1}') 192.168.5.162 192.168.5.92; resolvectl domain eth0 '~.'; echo 'DNS registered'"]
    volumes:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
    depends_on:
      ziti-router:
        condition: service_started
