services:
  ziti-router:
    image: netfoundry/autonomous-router:latest
    container_name: middleware_ziti_router
    restart: unless-stopped
    network_mode: host
    pid: host
    cap_add:
      - NET_ADMIN
    environment:
      - REG_KEY=${REG_KEY}
      - TUNNEL_MODE=auto
    volumes:
      - /docker/configs/netfoundry:/etc/netfoundry

  dns-register:
    image: ubuntu:24.04
    container_name: middleware_ziti_dns_register
    restart: "no"
    network_mode: host
    pid: host
    privileged: true
    entrypoint: ["/bin/bash", "-c", "sleep 45; nsenter -t 1 -m -- resolvectl dns eth0 192.168.5.148 192.168.5.162 192.168.5.92; nsenter -t 1 -m -- resolvectl domain eth0 '~.'; echo 'DNS registered'"]
    volumes: []
    depends_on:
      ziti-router:
        condition: service_started
