services:
  yourls:
    image: yourls
    restart: unless-stopped
    ports:
      - 8083:80
    environment:
      YOURLS_DB_PASS: ${YOURLS_DB_PASS}
      YOURLS_SITE: ${YOURLS_SITE}
      YOURLS_USER: ${YOURLS_USER}
      YOURLS_PASS: ${YOURLS_PASS}

  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${YOURLS_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: yourls
