[[server]]
name = "komodo_core"
tags = ["sync"]
[server.config]
address = "https://komodo-periphery:8120"
enabled = true

##

[[server]]
name = "media_servers"
tags = ["sync"]
[server.config]
address = "https://mediaservers.local:8120"
enabled = true

##

[[server]]
name = "middleware"
tags = ["sync"]
[server.config]
address = "https://middleware.local:8120"
enabled = true

##

[[server]]
name = "servarr"
tags = ["sync"]
[server.config]
address = "https://servarr.local:8120"
enabled = true

##

[[stack]]
name = "komodo_core_cloudflared"
tags = ["sync"]
[stack.config]
server = "komodo_core"
run_build = true
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
git_account = "nikolanovoselec"
repo = "nikolanovoselec/komodo"
run_directory = "komodo_core/cloudflared"
environment = """
 TOKEN = [[CFD_TOKEN_INGRESS]]
"""

##

[[stack]]
name = "middleware_authentik"
tags = ["sync"]
[stack.config]
server = "middleware"
run_build = true
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
git_account = "nikolanovoselec"
repo = "nikolanovoselec/komodo"
webhook_force_deploy = true
run_directory = "middleware/authentik"
environment = """
AUTHENTIK_POSTGRESQL__PASSWORD = [[AUTHENTIK_POSTGRESQL__PASSWORD]]
AUTHENTIK_SECRET_KEY = [[AUTHENTIK_SECRET_KEY]]
VERSION = 2025.2.4
"""

##

[[stack]]
name = "middleware_backrest"
tags = ["sync"]
[stack.config]
server = "middleware"
run_build = true
poll_for_updates = true
auto_update = true
destroy_before_deploy = true
git_account = "nikolanovoselec"
repo = "nikolanovoselec/komodo"
run_directory = "middleware/backrest"
environment = """
  HOSTNAME = backrest-middleware.local.graymatter.ch
"""

##

[[stack]]
name = "middleware_beszel"
tags = ["sync"]
[stack.config]
server = "middleware"
run_build = true
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
git_account = "nikolanovoselec"
repo = "nikolanovoselec/komodo"
run_directory = "middleware/beszel"
environment = """
KEY = [[BESZEL_KEY]]
"""

##

[[stack]]
name = "middleware_cloudflared"
tags = ["sync"]
[stack.config]
server = "middleware"
run_build = true
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
git_account = "nikolanovoselec"
repo = "nikolanovoselec/komodo"
run_directory = "middleware/cloudflared"
environment = """
 TOKEN = [[CFD_TOKEN_INGRESS]]
"""

##

[[stack]]
name = "middleware_dozzle"
tags = ["sync"]
[stack.config]
server = "middleware"
run_build = true
poll_for_updates = true
auto_update = true
destroy_before_deploy = true
git_account = "nikolanovoselec"
repo = "nikolanovoselec/komodo"
run_directory = "middleware/dozzle"

##

[[stack]]
name = "middleware_heimdall"
tags = ["sync"]
[stack.config]
server = "middleware"
run_build = true
poll_for_updates = true
auto_update = true
destroy_before_deploy = true
git_account = "nikolanovoselec"
repo = "nikolanovoselec/komodo"
run_directory = "middleware/heimdall"

##

[[stack]]
name = "middleware_npm"
tags = ["sync"]
[stack.config]
server = "middleware"
run_build = true
poll_for_updates = true
auto_update = true
destroy_before_deploy = true
git_account = "nikolanovoselec"
repo = "nikolanovoselec/komodo"
run_directory = "middleware/npm"

##

[[stack]]
name = "middleware_shlink"
tags = ["sync"]
[stack.config]
server = "middleware"
run_build = true
poll_for_updates = true
auto_update = true
destroy_before_deploy = true
git_account = "nikolanovoselec"
repo = "nikolanovoselec/komodo"
run_directory = "middleware/shlink"
environment = """
DEFAULT_DOMAIN = [[SHLINK_DEFAULT_DOMAIN]]
INITIAL_API_KEY = [[SHLINK_INITIAL_API_KEY]]
DB_USER = shlink
DB_PASSWORD = [[SHLINK_MARIADB_ROOT_PASSWORD]]
DEFAULT_INVALID_SHORT_URL_REDIRECT = https://xyz.tld
DEFAULT_REGULAR_404_REDIRECT = https://xyz.tld
DEFAULT_BASE_URL_REDIRECT = https://xyz.tld
SHLINK_SERVER_URL = [[SHLINK_SERVER_URL]]
SHLINK_SERVER_API_KEY = [[SHLINK_SERVER_API_KEY]]
MARIADB_ROOT_PASSWORD = [[SHLINK_MARIADB_ROOT_PASSWORD]]
MARIADB_USER = shlink
MARIADB_PASSWORD = [[SHLINK_MARIADB_ROOT_PASSWORD]]
MARIADB_DATABASE = shlink
"""

##

[[stack]]
name = "middleware_uptime_kuma"
tags = ["sync"]
[stack.config]
server = "middleware"
run_build = true
poll_for_updates = true
auto_update = true
destroy_before_deploy = true
git_account = "nikolanovoselec"
repo = "nikolanovoselec/komodo"
run_directory = "middleware/uptime_kuma/"

##

[[resource_sync]]
name = "secrets"
tags = ["sync"]
[resource_sync.config]
repo = "nikolanovoselec/secrets"
git_account = "nikolanovoselec"
resource_path = ["main.toml"]
managed = true
include_resources = false
include_variables = true

##

[[resource_sync]]
name = "servers_and_stacks"
tags = ["sync"]
[resource_sync.config]
repo = "nikolanovoselec/komodo"
git_account = "nikolanovoselec"
resource_path = ["main.toml"]
managed = true
match_tags = ["sync"]
include_user_groups = true