services:
    shlink_app:
        container_name: shlink_app
        image: shlinkio/shlink:stable
        restart: unless-stopped
        ports:
            - 8080:8080
        environment:
          - DEFAULT_DOMAIN=${DEFAULT_DOMAIN}
          - INITIAL_API_KEY=${INITIAL_API_KEY}
          - DB_DRIVER=maria
          - DB_NAME=shlink
          - DB_USER=shlink
          - DB_PASSWORD=shlink
          - DB_HOST=shlink_db
#          - DEFAULT_INVALID_SHORT_URL_REDIRECT=${DEFAULT_INVALID_SHORT_URL_REDIRECT}
#          - DEFAULT_REGULAR_404_REDIRECT=${DEFAULT_REGULAR_404_REDIRECT}
#          - DEFAULT_BASE_URL_REDIRECT=${DEFAULT_BASE_URL_REDIRECT}
          - GEOLITE_LICENSE_KEY=${GEOLITE_LICENSE_KEY}
        depends_on:
          - shlink_db
        labels:
          com.centurylinklabs.watchtower.enable: "true"

    shlink_web_client:
        container_name: shlink_web_client
        image: shlinkio/shlink-web-client:stable
        restart: unless-stopped
        ports:
            - 8081:8080
        environment:
          - SHLINK_SERVER_URL=${SHLINK_SERVER_URL}
          - SHLINK_SERVER_API_KEY=${SHLINK_SERVER_API_KEY}
        depends_on:
          - shlink_app
        labels:
          com.centurylinklabs.watchtower.enable: "true"

    shlink_db:
        container_name: shlink_db
        image: mariadb:lts
        restart: unless-stopped
        volumes:
            - /mnt/configs/shlink/db_data:/var/lib/mysql
        environment:
          - MARIADB_ROOT_PASSWORD=shlink
          - MARIADB_USER=shlink
          - MARIADB_PASSWORD=shlink
          - MARIADB_DATABASE=shlink
          - MYSQL_INITDB_SKIP_TZINFO=1
          - MARIADB_AUTO_UPGRADE=1
        labels:
          com.centurylinklabs.watchtower.enable: "true"