services:
    shlink_app:
        container_name: middleware_shlink_server
        image: shlinkio/shlink:stable
        restart: unless-stopped
        ports:
            - 8080:8080
        environment:
          - DEFAULT_DOMAIN=${DEFAULT_DOMAIN}
          - INITIAL_API_KEY=${INITIAL_API_KEY}
          - DB_DRIVER=maria
          - DB_NAME=shlink
          - DB_USER=${DB_USER}
          - DB_PASSWORD=${DB_PASSWORD}
          - DB_HOST=shlink_db
          - DEFAULT_INVALID_SHORT_URL_REDIRECT=${SHLINK_DEFAULT_INVALID_SHORT_URL_REDIRECT}
          - DEFAULT_REGULAR_404_REDIRECT=${SHLINK_DEFAULT_REGULAR_404_REDIRECT}
          - DEFAULT_BASE_URL_REDIRECT=${SHLINK_DEFAULT_BASE_URL_REDIRECT}
        depends_on:
          - shlink_db
        network_mode: bridge

    shlink_web_client:
        container_name: middleware_shlink_web_client
        image: shlinkio/shlink-web-client:stable
        restart: unless-stopped
        ports:
            - 8081:8080
        environment:
          - SHLINK_SERVER_URL=${SHLINK_SERVER_URL}
          - SHLINK_SERVER_API_KEY=${SHLINK_SERVER_API_KEY}
        depends_on:
          - shlink_app
        network_mode: bridge

    shlink_db:
        container_name: middleware_shlink_database
        image: mariadb:lts
        restart: unless-stopped
        volumes:
            - /mnt/configs/shlink/db_data:/var/lib/mysql
        environment:
          - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
          - MARIADB_USER=${MARIADB_USER}
          - MARIADB_PASSWORD=${MARIADB_PASSWORD}
          - MARIADB_DATABASE=${MARIADB_DATABASE}
          - MYSQL_INITDB_SKIP_TZINFO=1
          - MARIADB_AUTO_UPGRADE=1
        network_mode: bridge