services:
  shlink:
    image: shlinkio/shlink:stable
    restart: unless-stopped
    container_name: middleware_shlink_server
    environment:
      - TZ="Europe/Zurich"
      - DEFAULT_DOMAIN=${DEFAULT_DOMAIN}
      - IS_HTTPS_ENABLED=false
      - GEOLITE_LICENSE_KEY=${GEOLITE_LICENSE_KEY}
      - DB_DRIVER=maria
      - DB_USER=shlink
      - DB_NAME=shlink
      - DB_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - DB_HOST=database
    depends_on:
      - database
    ports:
      - 8080:8080

  database:
    image: mariadb:10.11
    restart: unless-stopped
    container_name: middleware_shlink_database
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=shlink
      - MARIADB_USER=shlink
      - MARIADB_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - /mnt/configs/shlink/db:/var/lib/mysql

  shlink-web-client:
    image: shlinkio/shlink-web-client:stable
    restart: unless-stopped
    container_name: middleware_shlink_gui
    volumes:
      - /mnt/configs/shlink:/usr/share/nginx/html
    depends_on:
      - shlink
    ports:
      - 8081:8080