### Once deployed, generate a working API key within the shlink_app container with "shlink api-key:generate"

services:
    shlink_app:
        container_name: middleware_shlink_server
        image: shlinkio/shlink:4.4.2
        restart: unless-stopped
#        user: 0:0
        ports:
            - 8080:8080
        environment:
          - DEFAULT_DOMAIN=${DEFAULT_DOMAIN}
          - INITIAL_API_KEY=${INITIAL_API_KEY}
          - DB_DRIVER=sqlite
#          - DB_NAME=shlink
#          - DB_USER=shlink
#          - DB_PASSWORD=${MARIADB_USER_PASSWORD}
#          - DB_HOST=shlink_db
          - DEFAULT_INVALID_SHORT_URL_REDIRECT=https://github.com/nikolanovoselec
          - DEFAULT_REGULAR_404_REDIRECT=https://github.com/nikolanovoselec
          - DEFAULT_BASE_URL_REDIRECT=https://github.com/nikolanovoselec
          - SHELL_VERBOSITY=3
#        depends_on:
#          - shlink_db

    shlink_web_client:
        container_name: middleware_shlink_admin
        image: shlinkio/shlink-web-client:4.3
        restart: unless-stopped
#        user: 0:0
        ports:
#            - 8081:8080
        environment:
          - SHLINK_SERVER_URL=https://${DEFAULT_DOMAIN}
          - SHLINK_SERVER_API_KEY=${INITIAL_API_KEY}
        depends_on:
          - shlink_app

#    shlink_db:
#        container_name: middleware_shlink_database
#        image: mariadb:10.7
#        restart: unless-stopped
#        user: 0:0
#        ports:
#            - "3308:3306"
#        volumes:
#            - /mnt/configs/shlink:/var/lib/mysql
#        environment:
#          - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
#          - MARIADB_USER=shlink
#          - MARIADB_PASSWORD=${MARIADB_USER_PASSWORD}
#          - MARIADB_DATABASE=shlink
#          - MYSQL_INITDB_SKIP_TZINFO=1
#          - MARIADB_AUTO_UPGRADE=1
