### Once deployed, generate a working API key within the shlink_app container with "shlink api-key:generate"

services:
    shlink_app:
        container_name: middleware_shlink_server
        image: shlinkio/shlink:latest
        restart: unless-stopped
        ports:
            - 8080:8080
        environment:
          - DEFAULT_DOMAIN=${DEFAULT_DOMAIN}
          - INITIAL_API_KEY=${INITIAL_API_KEY}
          - IS_HTTPS_ENABLED=true
          - DEFAULT_INVALID_SHORT_URL_REDIRECT=https://github.com/nikolanovoselec
          - DEFAULT_REGULAR_404_REDIRECT=https://github.com/nikolanovoselec
          - DEFAULT_BASE_URL_REDIRECT=https://github.com/nikolanovoselec

    shlink_web_client:
        container_name: middleware_shlink_admin
        image: shlinkio/shlink-web-client:latest
        restart: unless-stopped
        ports:
            - 8081:8080
        environment:
          - SHLINK_SERVER_URL=https://${DEFAULT_DOMAIN}
        depends_on:
          - shlink_app
