services:
  uptime-kuma:
    restart: unless-stopped
    container_name: middleware_uptime_kuma
    ports:
      - 3001:3001
    volumes:
      - /mnt/configs/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    image: louislam/uptime-kuma:latest
    network_mode: bridge