services:
  ombi:
    image: lscr.io/linuxserver/ombi:v4.53.4-ls246
    container_name: servarr_ombi
    dns:
      - 100.64.0.2
      - 192.168.5.162
      - 192.168.5.92
    environment:
      - TZ=Europe/Zurich
    volumes:
      - /docker/configs/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped
    network_mode: bridge
