services:
  unpackerr:
    image: golift/unpackerr:latest
    container_name: storage_unpackerr
    volumes:
      - /volume1/video/:/data
    restart: unless-stopped
    user: 1026:100 #syno user
    environment:
      - TZ=Europe/Zurich
      - UN_LOG_FILE=/data/unpackerr.log
      - UN_SONARR_0_URL=http://servarr.local:8988
      - UN_SONARR_0_API_KEY=${SONARR_API_KEY}
      - UN_RADARR_0_URL=http://servarr.local:8309
      - UN_RADARR_0_API_KEY=${RADARR_API_KEY}
      - UN_FOLDER_0_PATH=/data/download/Unpackerr
      - UN_FOLDER_EXTRACT_PATH=/data/download/Unpackerr
      - UN_FOLDER_0_DISABLE_RECURSION=true
      - UN_FOLDER_MOVE_BACK=true
    network_mode: host