services:
  dozzle-agent:
    image: amir20/dozzle:v10.1.2
    container_name: openziti_i_dozzle_agent
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 6007:7007
    restart: unless-stopped
    environment:
    - DOZZLE_HOSTNAME=openziti_i
    network_mode: bridge
