services:
    pihole:
      image: pihole/pihole:2025.10.2
      container_name: storage_pihole
      restart: unless-stopped
      ports:
        - 53:53/tcp
        - 53:53/udp
        - 81:80
      volumes:
        - /volume1/docker/_synology_configs/pihole_stubby:/etc/pihole
      environment:
        - TZ=Europe/Zurich
        - PIHOLE_UID=1026
        - PIHOLE_GID=100
        - FTLCONF_webserver_api_password=${PIHOLE_API_KEY}
#        - FTLCONF_dns_upstreams=127.0.0.1#8053
        - FTLCONF_dns_listeningMode=ALL
        - IPv6=false
        - WEBUIBOXEDLAYOUT=traditional
        - WEBTHEME=default-auto
        - DNSMASQ_USER=root
      cap_add:
        - CAP_SYS_TIME
        - CAP_SYS_NICE
      network_mode: bridge