services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        container_name: storage_transmission
        volumes:
            - /volume1/video/:/data
            - /volume1/docker/_synology_configs/transmission:/config
            - /volume1/docker/_synology_configs/transmission/ovpn-config/:/etc/openvpn/custom/
        environment:
            - OPENVPN_PROVIDER=CUSTOM
            - OPENVPN_CONFIG=default
            - OPENVPN_USERNAME=${OPENVPN_USERNAME}
            - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
            - LOCAL_NETWORK=192.168.0.0/16
            - CREATE_TUN_DEVICE=true
            - TZ=Europe/Berlin
            - HEALTH_CHECK_HOST=google.com
            - TRANSMISSION_WEB_UI=transmissionic
            - ENABLE_UFW=false
            - PEER_DNS=true
            - TRANSMISSION_PEER_PORT=32323
            - TRANSMISSION_RPC_USERNAME=${TRANSMISSION_RPC_USERNAME}
            - TRANSMISSION_RPC_PASSWORD=${TRANSMISSION_RPC_PASSWORD}
            - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
            - TRANSMISSION_DOWNLOAD_DIR=/data/download/_OVPN/completed
            - TRANSMISSION_INCOMPLETE_DIR=/data/download/_OVPN/incomplete
            - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        restart: unless-stopped 
        image: haugene/transmission-openvpn:5.3.2
