services:
    profilarr:
        image: santiagosayshey/profilarr:latest # Use :beta for early access to new features
        container_name: servarr_profilarr
        ports:
            - 6868:6868
        volumes:
            - /mnt/configs/profilarr:/config # Replace with your actual path
        environment:
            - TZ=Europe/Zurich # Set your timezone
        restart: unless-stopped