services:
  yourls-app:
    image: tiredofit/yourls:latest
    container_name: middleware_yourls_app
    links:
      - yourls-db
    volumes:
      - /mnt/config/yourls/logs/:/www/logs
    environment:
      - VIRTUAL_HOST=yourls.local.graymatter.ch
      - VIRTUAL_PORT=80
      - DB_HOST=yourls-db
      - DB_NAME=yourls
      - DB_USER=yourls
      - DB_PASS=${YOURLS_DB_PASS}
      - SITE_NAME=${YOURLS_SITE}
      - ADMIN_USER=admin
      - ADMIN_PASS=${ADMIN_PASS}
      - DEBUG=false
    ports:
      - 8123:80
    restart: unless-stopped

  yourls-db:
    image: tiredofit/mariadb:latest
    container_name: middleware_yourls_database
    volumes:
      - /mnt/config/yourls/db:/var/lib/mysql
    environment:
      - ROOT_PASS=${ADMIN_PASS}
      - DB_NAME=yourls
      - DB_USER=yourls
      - DB_PASS=${YOURLS_DB_PASS}
    restart: unless-stopped
