services:
   yourls:
     image: yourls:latest
     container_name: middleware_yourls_server
     restart: unless-stopped
     ports:
       - 8083:80
     environment:
       YOURLS_DB_PASS: ${YOURLS_MYSQL_ROOT_PASSWORD}
       YOURLS_SITE: ${YOURLS_SITE}
       YOURLS_USER: ${YOURLS_USER}
       YOURLS_PASS: ${YOURLS_PASS}
 
   mysql:
     image: mysql
     container_name: middleware_yourls_database
     restart: unless-stopped
     environment:
       MYSQL_ROOT_PASSWORD: ${YOURLS_MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: yourls