services:
  emby:
    image: lscr.io/linuxserver/emby:4.9.3.0-ls278
    container_name: media_servers_emby
    network_mode: host #for local/remote stream discovery
    environment:
      - TZ=Europe/Zurich
    volumes:
      - /docker/configs/emby:/config
      - /mnt/unas/Shows/:/mnt/synology/tv shows/
      - /mnt/unas/Movies/:/mnt/synology/movies/
      - /mnt/unas/Music/Library:/music
      - /mnt/video/Backup/Emby/:/mnt/synology/backup/
#    ports:
#      - 8093:8096 #not needed when running on host
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
