services:
  dozzle-agent:
    image: amir20/dozzle:v8.14.2
    command: agent
    container_name: storage_dozzle_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
    environment:
    - DOZZLE_HOSTNAME=storage
    restart: unless-stopped
    network_mode: bridge
