services:
  it-tools:
    image: 'corentinth/it-tools:2024.10.22-7ca5933'
    ports:
      - '8081:80'
    restart: unless-stopped
    container_name: tools_it_tools
    #dns:
    #  - 100.64.0.2
    #  - 192.168.5.162
    #  - 192.168.5.92
    network_mode: bridge
