services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:v0.11.1
    container_name: dns_ntp_nebula_sync
    environment:
    - PRIMARY=http://pihole-master.local|${PIHOLE_API_KEY}
    - REPLICAS=http://pihole-slave.local|${PIHOLE_API_KEY},http://nas.local:81|${PIHOLE_API_KEY}
    - FULL_SYNC=true
    - RUN_GRAVITY=false
    - CRON=1 * * * *
    - CLIENT_RETRY_DELAY_SECONDS=20
    - TIMEZONE=Europe/Zurich
    restart: unless-stopped
    network_mode: bridge
