services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: dns_ntp_nebula_sync
    environment:
    - PRIMARY=http://192.168.5.162|${PIHOLE_API_KEY}
    - REPLICAS=http://192.168.5.92|${PIHOLE_API_KEY} #,http://192.168.5.162|${PIHOLE_API_KEY}
    - FULL_SYNC=true
    - RUN_GRAVITY=false
    - CRON=1 * * * *
#    dns:
#    - 192.168.111.1
    restart: unless-stopped
    network_mode: bridge