services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: dns_ntp_nebula_sync
    environment:
    - PRIMARY=https://pihole-master.local|${PIHOLE_API_KEY}
    - REPLICAS=https://pihole-slave.local|${PIHOLE_API_KEY} #,http://192.168.5.162|${PIHOLE_API_KEY}
    - FULL_SYNC=true
    - RUN_GRAVITY=false
    - CRON=1 * * * *
    - CLIENT_SKIP_TLS_VERIFICATION=1
    - CLIENT_RETRY_DELAY_SECONDS=20
 #   dns:
 #   - 192.168.5.162
 #   - 192.168.5.92
    restart: unless-stopped
    network_mode: bridge