services:
    agent:
        image: 'portainer/agent:2.40.0'
        volumes:
            - '/:/host'
            - '/var/lib/docker/volumes:/var/lib/docker/volumes'
            - '/var/run/docker.sock:/var/run/docker.sock'
        restart: unless-stopped
        container_name: komodo_core_portainer_agent
        dns:
            - 100.64.0.2
            - 192.168.5.162
            - 192.168.5.92
        ports:
            - '9001:9001'
        network_mode: bridge
