services:
  dozzle-agent:
    image: amir20/dozzle:latest
    command: agent
    container_name: komodo_core_dozzle_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
    #labels:
    #  com.centurylinklabs.watchtower.enable: "true"
    #  watchtower
    restart: unless-stopped
    network_mode: bridge