services:
  backrest:
    image: garethgeorge/backrest:v1.9.2
    container_name: middleware_backrest
    hostname: backrest-middleware.local.graymatter.ch
    volumes:
      - /docker/configs/backrest/data:/data
      - /docker/configs/backrest/config:/config
      - /docker/configs/backrest/cache:/cache
      - /docker/configs/backrest/tmp:/tmp
      - /docker/configs/:/userdata  #Local path to be backed up
      - /mnt/docker/_restic_backup_repository/:/repos #NFS mount of remote repository
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=Europe/Zurich
    ports:
      - "9898:9898"
    restart: unless-stopped
    network_mode: bridge
