services:
  ziti-host:
    image: openziti/ziti-host:1.11.2
    container_name: middleware_ziti_tunneler_ziti_host
    restart: unless-stopped
    environment:
      - ZITI_ENROLL_TOKEN=${ZITI_ENROLL_TOKEN}
    volumes:
      - /docker/configs/ziti-host:/ziti-edge-tunnel
