services:
  wizarr:
    container_name: servarr_wizarr
    image: ghcr.io/wizarrrr/wizarr:v2025.10.6
    ports:
      - 5690:5690
    volumes:
      - /docker/configs/wizarr/database:/data/database
      - /docker/configs/wizarr/wizard:/data/wizard_steps
    environment:
      - PUID=1000 #Set UID
      - PGID=1000 #Set GID
      - DISABLE_BUILTIN_AUTH=false #Set to true ONLY if you are using another auth provider (Authelia, Authentik, etc)
      - TZ=Europe/Zurich #Set your timezone here
    restart: unless-stopped
