services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:v1.5.6-ls342
    container_name: servarr_bazarr
    dns:
      - 100.64.0.2
      - 192.168.5.162
      - 192.168.5.92
    environment:
      - TZ=Europe/Zurich
      - PUID=1026
      - PGID=100
    volumes:
      - /docker/configs/bazarr:/config
      - /mnt/synology:/data
    ports:
      - 6767:6767
    restart: unless-stopped
    network_mode: bridge
