services:
  backrest:
    image: garethgeorge/backrest:v1.12.1
    container_name: komodo_core_backrest
    #dns:
    #  - 100.64.0.2
    #  - 192.168.5.162
    #  - 192.168.5.92
    hostname: backrest-komodo.local.graymatter.ch
    volumes:
      - /docker/configs/backrest/data:/data
      - /docker/configs/backrest/config:/config
      - /docker/configs/backrest/cache:/cache
      - /docker/configs/backrest/tmp:/tmp
      - /docker/configs/:/userdata #Mount local paths to be backed up
      - /mnt/unas/Backup/Restic:/repos #NFS mount of the UNAS restic repository
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=Europe/Zurich
    ports:
      - "9898:9898"
    restart: unless-stopped
    network_mode: bridge
