services:
  backrest:
    image: garethgeorge/backrest:v1.10.0
    container_name: komodo_core_backrest
    hostname: backrest-komodo.local.graymatter.ch
    volumes:
      - /docker/configs/backrest/data:/data
      - /docker/configs/backrest/config:/config
      - /docker/configs/backrest/cache:/cache
      - /docker/configs/backrest/tmp:/tmp
      - /docker/configs/:/userdata #Mount local paths to be backed up
      - /mnt/docker/_restic_backup_repository/:/repos #NFS mount of the backrest repository
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=Europe/Zurich
    ports:
      - "9898:9898"
    restart: unless-stopped
    network_mode: bridge
