services:
  dozzle-agent:
    image: amir20/dozzle:v8.14.4
    container_name: minecraft_dozzle_agent
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
    restart: unless-stopped
    environment:
    - DOZZLE_HOSTNAME=minecraft
    network_mode: bridge
