services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:v2.17.1-ls229
    container_name: media_servers_tautulli
    #dns:
    #  - 100.64.0.2
    #  - 192.168.5.162
    #  - 192.168.5.92
    environment:
      - TZ=Europe/Zurich
    volumes:
      - /docker/configs/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped
    network_mode: bridge
