services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.3.5.5327-ls144
    container_name: servarr_prowlarr
    #dns:
    #  - 100.64.0.2
    #  - 192.168.5.162
    #  - 192.168.5.92
    environment:
      - TZ=Europe/Zurich
    volumes:
      - /docker/configs/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    network_mode: bridge
