services:
  beszel-agent:
    image: "henrygd/beszel-agent:0.15.0"
    container_name: servarr_beszel_agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks or partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
      - /docker/configs/beszel/sys:/mnt/sys
    environment:
      LISTEN: 45876
      KEY: ${BESZEL_KEY}
      SYS_SENSORS: /mnt/sys
