services:
  dynacat:
    image: panonim/dynacat:3.0.0
    container_name: tools_dynacat
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
    environment:
      LOG_LEVEL: INFO
      ENABLE_EDITOR: "false"
    restart: unless-stopped
    network_mode: bridge
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
