services:
    agent-zero-run:
        image: frdel/agent-zero-run:latest
        container_name: tools_agent_zero
        volumes:
            - /mnt/configs/agent_zero:/a0
        ports:
            - '8888:80'
        network_mode: bridge