services:
  termix:
    image: ghcr.io/lukegus/termix:release-1.7.3
    container_name: termix
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /docker/configs/termix:/app/data
    environment:
      PORT: "8080"