---
services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: middleware_nebula_sync
    environment:
    - PRIMARY=http://pihole-master.local|${PIHOLE_API_KEY}
    - REPLICAS=http://pihole-slave.local|${PIHOLE_API_KEY} #,http://192.168.5.33|${PIHOLE_API_KEY}
    - FULL_SYNC=true
    - RUN_GRAVITY=false
    - CRON=1 * * * *
