services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: middleware_nebula_sync
    environment:
    - PRIMARY=http://192.168.5.163|${PIHOLE_API_KEY}
    - REPLICAS=http://192.168.5.162|${PIHOLE_API_KEY},http://192.168.5.92|${PIHOLE_API_KEY}
    - FULL_SYNC=true
    - RUN_GRAVITY=false
    - CRON=1 * * * *
    restart: unless-stopped
    network_mode: bridge