services:
  server:
    image: kutt/kutt:latest
    container_name: middleware_kutt
    volumes:
       - /mnt/configs/kutt/db:/var/lib/kutt
       - /mnt/configs/kutt:/kutt/custom
    environment:
      DB_FILENAME: "/var/lib/kutt/data.sqlite"
      DEFAULT_DOMAIN: ${DEFAULT_DOMAIN}
      TRUST_PROXY: true
      CUSTOM_DOMAIN_USE_HTTPS: true
      MAIL_ENABLED: true
    ports:
      - 3000:3000
    network_mode: bridge