services:
  server:
    build:
      context: .
    container_name: middleware_kutt
    volumes:
       - /mnt/configs/kutt/db:/var/lib/kutt
       - /mnt/configs/kutt:/kutt/custom
    environment:
      DB_FILENAME: "/var/lib/kutt/data.sqlite"
    ports:
      - 3743:3000