services:
  watchtower:
    image: containrrr/watchtower
    container_name: uptime_kuma
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Zurich
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_SCHEDULE=0 0 2 * * *
      - WATCHTOWER_TIMEOUT=30s
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_REMOVE_VOLUMES=true
    restart: unless-stopped
