services:
  ziti-router:
    image: openziti/ziti-router:1.6.14
    container_name: openziti_ii_fabric_router
    restart: unless-stopped
    network_mode: host
    dns:
      - 192.168.5.162
    environment:
      - ZITI_ENROLL_TOKEN=${ZITI_ENROLL_TOKEN}
      - ZITI_CTRL_ADVERTISED_ADDRESS=swisspost.cloudziti.io
      - ZITI_ROUTER_ADVERTISED_ADDRESS=openziti-fabric-ii.lan
      - ZITI_ROUTER_PORT=3022
      - ZITI_ROUTER_MODE=none
    volumes:
      - /docker/configs/ziti-router:/ziti-router
