services:
  grafana:
    image: grafana/grafana:latest
    container_name: tools_grafana
    restart: unless-stopped
    ports:
     - '3333:3000'
    volumes:
      - /mnt/configs/grafana:/var/lib/grafana