services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: pantlesscoding/flaresolverr:latest #experimental_version
    container_name: servarr_flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Zurich
      - DRIVER=nodriver
      - no_sandbox=true
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped 
    network_mode: bridge