services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.17.2952-ls309
    container_name: servarr_sonarr
    #dns:
    #  - 100.64.0.2
    #  - 192.168.5.162
    #  - 192.168.5.92
    environment:
      - PUID=977
      - PGID=988
      - UMASK=002
      - TZ=Europe/Zurich
    volumes:
      - /docker/configs/sonarr:/config
      - /mnt/unas:/data
    ports:
      - 8988:8989
    restart: unless-stopped
    network_mode: bridge
