services:
  autonomous-router:
    container_name: docker_ii_aer
    image: ghcr.io/nicfragale/autonomous-router:latest
    pull_policy: always
    restart: unless-stopped
    stop_grace_period: 30s
    network_mode: host
    pid: host
    cap_add:
      - NET_ADMIN
    environment:
      - REG_KEY=${REG_KEY}
      - TUNNEL_MODE=auto
      - DISABLE_AUTO_UPDATE=true
      - ZITI_VERSION_OVERRIDE=v1.7.2
      - HOSTS_ENTRIES=docker-ii.lan
    volumes:
      - ./ziti_router:/etc/netfoundry
      - /etc/systemd:/etc/systemd
      - /run/systemd:/run/systemd
      - /etc/hosts:/etc/hosts
